//! Hyprland: the managed Lua file, live application, and reading values back.

use super::gestures;
use super::lua::{self, quote};
use super::state::State;
use crate::{cmd, paths};
use anyhow::{Result, bail};
use serde_json::Value;
use std::collections::BTreeMap;

pub const HEADER: &str = "-- Generated by Settings (managed). Do not edit by hand: change values in the\n\
-- Settings app, or use a row's reset button to hand a value back to your own\n\
-- config. Delete this file and its require() line in hyprland.lua to remove it.\n";

pub const REQUIRE_LINE: &str = "require(\"hypr.settings\") -- Settings app (managed values, loaded last)";

/// Absolute path of this binary as other programs should call it.
pub fn self_command() -> String {
    let installed = paths::home().join(".local/bin/settings");
    if installed.exists() {
        return installed.to_string_lossy().into();
    }
    std::env::current_exe().map(|p| p.to_string_lossy().into_owned()).unwrap_or_else(|_| "settings".into())
}

pub fn generate(state: &State, self_cmd: &str) -> String {
    let mut out = String::from(HEADER);

    if !state.env.is_empty() {
        out.push_str("\n-- Environment\n");
        for (k, v) in &state.env {
            out.push_str(&format!("hl.env({}, {})\n", quote(k), quote(v)));
        }
    }

    if !state.options.is_empty() {
        out.push_str("\n-- Options\n");
        out.push_str(&format!("hl.config({})\n", lua::nested_table(&state.options)));
    }

    for (name, fields) in &state.devices {
        if fields.is_empty() {
            continue;
        }
        let mut parts = vec![format!("name = {}", quote(name))];
        parts.extend(fields.iter().map(|(k, v)| format!("{} = {}", lua::ident_or_key(k), lua::value(v))));
        out.push_str(&format!("hl.device({{ {} }})\n", parts.join(", ")));
    }

    for (output, m) in &state.monitors {
        let mut parts = vec![format!("output = {}", quote(output))];
        if m.disabled {
            parts.push("disabled = true".into());
        } else {
            parts.push(format!("mode = {}", quote(m.mode.as_deref().unwrap_or("preferred"))));
            parts.push(format!("position = {}", quote(m.position.as_deref().unwrap_or("auto"))));
            parts.push(format!("scale = {}", lua::value(&serde_json::json!(m.scale.unwrap_or(1.0)))));
            if let Some(t) = m.transform {
                parts.push(format!("transform = {t}"));
            }
        }
        if out.contains("\n-- Displays\n") {
            out.push_str(&format!("hl.monitor({{ {} }})\n", parts.join(", ")));
        } else {
            out.push_str(&format!("\n-- Displays\nhl.monitor({{ {} }})\n", parts.join(", ")));
        }
    }

    if !state.autostart.is_empty() {
        out.push_str("\n-- Started with the session (once; reloads don't start another)\n");
        for (process, command) in &state.autostart {
            if !crate::backend::rules::valid_process(process) {
                continue;
            }
            out.push_str(&format!(
                "if not o.shell_succeeds({}) then hl.exec_cmd({}) end\n",
                quote(&format!("pgrep -x {process}")),
                quote(command)
            ));
        }
    }

    let rule_lines: Vec<String> = state
        .window_rules
        .iter()
        .filter_map(|r| super::rules::lua_line(false, r))
        .chain(state.layer_rules.iter().filter_map(|r| super::rules::lua_line(true, r)))
        .collect();
    if !rule_lines.is_empty() {
        out.push_str("\n-- Window and layer rules\n");
        for line in rule_lines {
            out.push_str(&line);
            out.push('\n');
        }
    }

    let gesture_lines = gestures::lua(&state.gestures);
    if !gesture_lines.is_empty() {
        out.push_str("\n-- Trackpad gestures\n");
        for line in gesture_lines {
            out.push_str(&line);
            out.push('\n');
        }
    }

    let max = state.max_volume.unwrap_or(100);
    let mut binds = String::new();
    if max > 100 {
        // Omarchy's keys stop at 100%; route them through Settings to go louder.
        for (keys, desc, arg) in [
            ("XF86AudioRaiseVolume", "Volume up", "raise"),
            ("XF86AudioLowerVolume", "Volume down", "lower"),
            ("ALT + XF86AudioRaiseVolume", "Volume up precise", "+1"),
            ("ALT + XF86AudioLowerVolume", "Volume down precise", "-1"),
        ] {
            binds.push_str(&format!("hl.unbind({})\n", quote(keys)));
            binds.push_str(&format!(
                "hl.bind({}, hl.dsp.exec_cmd({}), {{ locked = true, repeating = true, description = {} }})\n",
                quote(keys),
                quote(&format!("{self_cmd} --volume {arg}")),
                quote(desc)
            ));
        }
    }
    for key in &state.unbinds {
        binds.push_str(&format!("hl.unbind({})\n", quote(key)));
    }
    for b in &state.binds {
        if b.keys.trim().is_empty() || b.command.trim().is_empty() {
            continue;
        }
        binds.push_str(&format!("hl.unbind({})\n", quote(&b.keys)));
        binds.push_str(&format!(
            "hl.bind({}, hl.dsp.exec_cmd({}), {{ description = {} }})\n",
            quote(&b.keys),
            quote(&b.command),
            quote(&b.description)
        ));
    }
    if !binds.is_empty() {
        out.push_str("\n-- Keybindings\n");
        out.push_str(&binds);
    }
    out
}

pub fn write(state: &State) -> Result<()> {
    let text = generate(state, &self_command());
    cmd::atomic_write(&paths::managed_lua(), &text)?;
    ensure_required()?;
    Ok(())
}

/// Make sure hyprland.lua loads the managed file, last.
pub fn ensure_required() -> Result<()> {
    let path = paths::hyprland_lua();
    let Ok(text) = std::fs::read_to_string(&path) else {
        bail!("{} not found", path.display());
    };
    if is_required(&text) {
        return Ok(());
    }
    let backup = path.with_extension(format!("lua.settings-bak.{}", timestamp()));
    std::fs::copy(&path, backup)?;
    let mut next = text.trim_end().to_string();
    next.push_str("\n\n");
    next.push_str(REQUIRE_LINE);
    next.push('\n');
    cmd::atomic_write(&path, &next)
}

pub fn is_required(text: &str) -> bool {
    text.lines().any(|l| {
        let l = l.trim();
        !l.starts_with("--") && (l.contains("require(\"hypr.settings\")") || l.contains("require('hypr.settings')"))
    })
}

pub fn timestamp() -> String {
    std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs().to_string()).unwrap_or_default()
}

pub fn eval(code: &str) -> Result<()> {
    let out = cmd::run(&["hyprctl", "eval", code])?;
    let t = out.trim();
    if !t.is_empty() && t != "ok" && t.to_lowercase().contains("error") {
        bail!("{t}");
    }
    Ok(())
}

/// Apply one option immediately without a reload.
pub fn apply_option(key: &str, value: &Value) -> Result<()> {
    let mut one = BTreeMap::new();
    one.insert(key.to_string(), value.clone());
    eval(&format!("hl.config({})", lua::nested_table_inline(&one)))
}

pub fn reload() {
    cmd::spawn(&["hyprctl", "reload"]);
}

/// Read an option's live value. Dotted keys are accepted.
pub fn get_option(key: &str) -> Option<Value> {
    let colon = key.replace('.', ":");
    let text = cmd::output(&["hyprctl", "-j", "getoption", &colon])?;
    let v: Value = serde_json::from_str(&text).ok()?;
    for field in ["bool", "int", "float", "str", "css", "custom", "vec2"] {
        if let Some(x) = v.get(field) {
            return Some(x.clone());
        }
    }
    None
}

pub fn get_bool(key: &str) -> Option<bool> {
    match get_option(key)? {
        Value::Bool(b) => Some(b),
        Value::Number(n) => Some(n.as_i64() != Some(0)),
        _ => None,
    }
}

pub fn get_f64(key: &str) -> Option<f64> {
    match get_option(key)? {
        Value::Number(n) => n.as_f64(),
        Value::String(s) => s.split_whitespace().next()?.parse().ok(),
        Value::Bool(b) => Some(if b { 1.0 } else { 0.0 }),
        _ => None,
    }
}

pub fn get_str(key: &str) -> Option<String> {
    match get_option(key)? {
        Value::String(s) => Some(s),
        other => Some(other.to_string()),
    }
}

pub fn json(args: &[&str]) -> Option<Value> {
    let mut full = vec!["hyprctl", "-j"];
    full.extend_from_slice(args);
    serde_json::from_str(&cmd::output(&full)?).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::state::Bind;
    use serde_json::json;

    #[test]
    fn empty_state_is_just_the_header() {
        assert_eq!(generate(&State::default(), "settings"), HEADER);
    }

    #[test]
    fn writes_options_devices_binds() {
        let mut s = State::default();
        s.options.insert("input.touchpad.tap_to_click".into(), json!(true));
        s.options.insert("general.gaps_in".into(), json!(4));
        s.devices.entry("my-mouse".into()).or_default().insert("sensitivity".into(), json!(-0.3));
        s.binds.push(Bind { keys: "SUPER + ALT + K".into(), description: "Kitty".into(), command: "kitty".into() });
        s.unbinds.push("SUPER + J".into());
        let out = generate(&s, "settings");
        assert!(out.contains("tap_to_click = true"));
        assert!(out.contains("gaps_in = 4"));
        assert!(out.contains("hl.device({ name = \"my-mouse\", sensitivity = -0.3 })"));
        assert!(out.contains("hl.unbind(\"SUPER + J\")"));
        assert!(out.contains("hl.bind(\"SUPER + ALT + K\", hl.dsp.exec_cmd(\"kitty\"), { description = \"Kitty\" })"));
    }

    #[test]
    fn louder_volume_rebinds_keys() {
        let mut s = State::default();
        assert!(!generate(&s, "settings").contains("XF86AudioRaiseVolume"));
        s.max_volume = Some(150);
        let out = generate(&s, "/x/settings");
        assert!(out.contains("hl.unbind(\"XF86AudioRaiseVolume\")"));
        assert!(out.contains("/x/settings --volume raise"));
    }

    #[test]
    fn detects_require_line() {
        assert!(is_required("require(\"hypr.settings\") -- x"));
        assert!(!is_required("-- require(\"hypr.settings\")"));
        assert!(!is_required("require(\"hypr.omasettings\")"));
    }
}
