//! Keyboard backlight timeout.
//!
//! A small helper (`settings --kbd-idle`, run as the `settings-kbd-idle` user
//! service) asks the compositor to tell it when there has been no keyboard or
//! pointer input for a while (the Wayland `ext-idle-notify` protocol), switches
//! the backlight off, and puts it back on the next input.

use crate::{cmd, paths};
use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use wayland_client::globals::{GlobalListContents, registry_queue_init};
use wayland_client::protocol::{wl_registry, wl_seat};
use wayland_client::{Connection, Dispatch, Proxy, QueueHandle};
use wayland_protocols::ext::idle_notify::v1::client::ext_idle_notification_v1::{self, ExtIdleNotificationV1};
use wayland_protocols::ext::idle_notify::v1::client::ext_idle_notifier_v1::ExtIdleNotifierV1;

pub const UNIT: &str = "settings-kbd-idle.service";

/// Choices offered in the UI, in seconds. 0 means never.
pub const CHOICES: &[(u32, &str)] = &[
    (0, "Never"),
    (5, "5 seconds"),
    (10, "10 seconds"),
    (15, "15 seconds"),
    (30, "30 seconds"),
    (60, "1 minute"),
    (120, "2 minutes"),
    (300, "5 minutes"),
    (600, "10 minutes"),
];

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct Config {
    /// Turn the backlight off after this many idle seconds; 0 leaves it alone.
    pub timeout_secs: u32,
}

pub fn config_file() -> PathBuf {
    paths::app_dir().join("keyboard-idle.toml")
}

pub fn unit_file() -> PathBuf {
    paths::config_home().join("systemd/user").join(UNIT)
}

pub fn load() -> Config {
    std::fs::read_to_string(config_file()).ok().and_then(|t| toml::from_str(&t).ok()).unwrap_or_default()
}

/// Keyboard backlight LEDs the kernel exposes (`asus::kbd_backlight`, `tpacpi::kbd_backlight`, …).
pub fn leds() -> Vec<String> {
    let Ok(entries) = std::fs::read_dir("/sys/class/leds") else { return vec![] };
    let mut names: Vec<String> =
        entries.flatten().map(|e| e.file_name().to_string_lossy().to_string()).filter(|n| n.contains("kbd_backlight")).collect();
    names.sort();
    names
}

pub fn available() -> bool {
    !leds().is_empty() && cmd::present("brightnessctl")
}

fn read_brightness(led: &str) -> Option<u32> {
    std::fs::read_to_string(format!("/sys/class/leds/{led}/brightness")).ok()?.trim().parse().ok()
}

fn brightnessctl(args: &[&str]) {
    let _ = std::process::Command::new("brightnessctl")
        .args(args)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .status();
}

fn set_brightness(led: &str, value: u32) {
    brightnessctl(&["-q", "-d", led, "set", &value.to_string()]);
}

// Omarchy's lock screen turns the backlight off with `brightnessctl -s … set 0`
// and its wake step puts back whatever `brightnessctl -s` last saved. If the
// lock blanks while this helper has the light off, that saved level is 0, and
// waking would switch the light off again right after this turned it back on.
// So both directions keep brightnessctl's saved level at the real one.

/// Turn a light off, saving its level for brightnessctl's restore.
fn switch_off(led: &str) {
    brightnessctl(&["-q", "-s", "-d", led, "set", "0"]);
}

/// Save the light's current level for brightnessctl's restore.
fn save_level(led: &str) {
    brightnessctl(&["-q", "-s", "-d", led, "get"]);
}

fn saved_file() -> PathBuf {
    let dir = std::env::var_os("XDG_RUNTIME_DIR").map(PathBuf::from).unwrap_or_else(std::env::temp_dir);
    dir.join("settings-kbd-idle.json")
}

/// Turn the backlight off, remembering what it was (in the runtime dir, so a
/// stopped service can still put it back).
fn dim() {
    let mut saved: Vec<(String, u32)> = Vec::new();
    for led in leds() {
        if let Some(v) = read_brightness(&led).filter(|v| *v > 0) {
            saved.push((led.clone(), v));
            switch_off(&led);
        }
    }
    if !saved.is_empty()
        && let Ok(text) = serde_json::to_string(&saved)
    {
        let _ = std::fs::write(saved_file(), text);
    }
}

/// Put back what [`dim`] turned off. Does nothing if it didn't.
pub fn restore() -> Result<()> {
    let path = saved_file();
    let Ok(text) = std::fs::read_to_string(&path) else { return Ok(()) };
    let saved: Vec<(String, u32)> = serde_json::from_str(&text).unwrap_or_default();
    for (led, value) in saved {
        // Don't fight a brightness the user has already set since.
        if read_brightness(&led) == Some(0) {
            set_brightness(&led, value);
        }
        if read_brightness(&led).is_some_and(|v| v > 0) {
            save_level(&led);
        }
    }
    let _ = std::fs::remove_file(path);
    Ok(())
}

pub fn generate_unit(self_cmd: &str) -> String {
    format!(
        "# Generated by Settings (managed).\n\
         [Unit]\n\
         Description=Turn the keyboard backlight off when idle\n\
         After=graphical-session.target\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={self_cmd} --kbd-idle\n\
         ExecStopPost={self_cmd} --kbd-idle-restore\n\
         Restart=always\n\
         RestartSec=3\n\
         TimeoutStopSec=10\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n"
    )
}

/// Save the setting and start, restart or stop the helper to match.
pub fn apply(cfg: &Config) -> Result<()> {
    cmd::atomic_write(&config_file(), &toml::to_string_pretty(cfg)?)?;
    if cfg.timeout_secs == 0 {
        if unit_file().exists() {
            let _ = cmd::run(&["systemctl", "--user", "disable", "--now", UNIT]);
            let _ = std::fs::remove_file(unit_file());
            let _ = cmd::run(&["systemctl", "--user", "daemon-reload"]);
        }
        return Ok(());
    }
    cmd::atomic_write(&unit_file(), &generate_unit(&super::hypr::self_command()))?;
    cmd::run(&["systemctl", "--user", "daemon-reload"])?;
    cmd::run(&["systemctl", "--user", "enable", UNIT])?;
    cmd::run(&["systemctl", "--user", "restart", UNIT])?;
    Ok(())
}

pub fn running() -> bool {
    cmd::output(&["systemctl", "--user", "is-active", UNIT]).is_some_and(|s| s.trim() == "active")
}

/// Keep the service in step with the saved timeout: rewrite a stale unit (an
/// older version, or a moved binary) and start the helper if it isn't running.
/// Does nothing when no timeout is set.
pub fn ensure_running() {
    if load().timeout_secs == 0 || !available() {
        return;
    }
    let want = generate_unit(&super::hypr::self_command());
    let stale = std::fs::read_to_string(unit_file()).map_or(true, |t| t != want);
    if stale {
        let _ = cmd::atomic_write(&unit_file(), &want);
        let _ = cmd::run(&["systemctl", "--user", "daemon-reload"]);
        let _ = cmd::run(&["systemctl", "--user", "enable", UNIT]);
    }
    if stale || !running() {
        let _ = cmd::run(&["systemctl", "--user", "restart", UNIT]);
    }
}

// ----- The helper itself -----

struct Idle {
    dimmed: bool,
}

impl Dispatch<wl_registry::WlRegistry, GlobalListContents> for Idle {
    fn event(
        _: &mut Self,
        _: &wl_registry::WlRegistry,
        _: wl_registry::Event,
        _: &GlobalListContents,
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
    }
}

impl Dispatch<wl_seat::WlSeat, ()> for Idle {
    fn event(_: &mut Self, _: &wl_seat::WlSeat, _: wl_seat::Event, _: &(), _: &Connection, _: &QueueHandle<Self>) {}
}

impl Dispatch<ExtIdleNotifierV1, ()> for Idle {
    fn event(
        _: &mut Self,
        _: &ExtIdleNotifierV1,
        _: <ExtIdleNotifierV1 as wayland_client::Proxy>::Event,
        _: &(),
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
    }
}

impl Dispatch<ExtIdleNotificationV1, ()> for Idle {
    fn event(
        state: &mut Self,
        _: &ExtIdleNotificationV1,
        event: ext_idle_notification_v1::Event,
        _: &(),
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
        match event {
            ext_idle_notification_v1::Event::Idled if !state.dimmed => {
                state.dimmed = true;
                eprintln!("settings-kbd-idle: idle, turning the backlight off");
                dim();
            }
            ext_idle_notification_v1::Event::Resumed if state.dimmed => {
                state.dimmed = false;
                eprintln!("settings-kbd-idle: input, turning the backlight back on");
                let _ = restore();
            }
            _ => {}
        }
    }
}

/// Run until stopped: dim after the configured idle time, restore on input.
pub fn run_daemon() -> Result<()> {
    let cfg = load();
    if cfg.timeout_secs == 0 {
        bail!("no keyboard backlight timeout is set");
    }
    let conn = Connection::connect_to_env().context("no Wayland display to watch for idleness")?;
    let (globals, mut queue) = registry_queue_init::<Idle>(&conn).context("couldn't read the Wayland globals")?;
    let qh = queue.handle();
    let seat: wl_seat::WlSeat = globals.bind(&qh, 1..=1, ()).context("no seat")?;
    let notifier: ExtIdleNotifierV1 =
        globals.bind(&qh, 1..=2, ()).context("this compositor doesn't support idle notifications (ext-idle-notify)")?;
    let ms = cfg.timeout_secs.saturating_mul(1000);
    // Version 2 watches input only, so a video playing (which inhibits idle) doesn't keep the backlight lit.
    let _notification = if notifier.version() >= 2 {
        notifier.get_input_idle_notification(ms, &seat, &qh, ())
    } else {
        notifier.get_idle_notification(ms, &seat, &qh, ())
    };
    eprintln!("settings-kbd-idle: watching for {} s of no input", cfg.timeout_secs);
    // Recover from a previous run that was killed while dimmed.
    let _ = restore();
    let mut state = Idle { dimmed: false };
    loop {
        queue.blocking_dispatch(&mut state).context("lost the connection to the compositor")?;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_restores_on_stop() {
        let u = generate_unit("/home/u/.local/bin/settings");
        assert!(u.contains("ExecStart=/home/u/.local/bin/settings --kbd-idle\n"));
        assert!(u.contains("ExecStopPost=/home/u/.local/bin/settings --kbd-idle-restore\n"));
        assert!(u.contains("WantedBy=graphical-session.target"));
        assert!(u.contains("TimeoutStopSec=10"));
        assert!(u.contains("Restart=always"));
    }

    #[test]
    fn config_round_trips() {
        let c = Config { timeout_secs: 30 };
        let text = toml::to_string_pretty(&c).unwrap();
        assert_eq!(toml::from_str::<Config>(&text).unwrap(), c);
        assert_eq!(toml::from_str::<Config>("").unwrap(), Config::default());
    }

    #[test]
    fn choices_start_with_never() {
        assert_eq!(CHOICES[0].0, 0);
        assert!(CHOICES.windows(2).all(|w| w[0].0 < w[1].0));
    }
}
